name: On PR Run

on: pull_request

env:
  DEVOPS_DIR: .github/workflows

jobs:
  python-script:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: Test-organization-cicd/Test3
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install python dependencies
      run: | 
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: Check false-positive
      run: python ${{ env.DEVOPS_DIR }}/script.py
      shell: sh